name: 🔒 Protección de Producción

on:
  pull_request:
    branches:
      - main

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd backend && npm install --include=dev && npx prisma generate && npm run build

  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd frontend && npm install && npm run build
